openapi: "3.0.2"
info:
  title: tf_caseQuery_caseSubjectQuery_caseUpdate
  version: "1.0"
servers:
  - url: https://ocioplatform--regulatory.sandbox.my.salesforce.com

components:
  securitySchemes:
    Bearer-Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # global schema
    UnauthorizedResponse:
      type: object
      properties:
        message:
          type: string
          example: Session expired or invalid
        errorCode:
          type: string
          example: INVALID_SESSION_ID
    # case query
    # end case query
    caseQuerySubjectRequestBody:
      type: object
      description: List of salesforce case record id
      properties:
        ids:
          type: array
          items:
            type: string
      required:
        - "ids"
      example:
        ids:
          - 500D700000MGsqqIAD
          - 500D800000MGsqqIAD
    # case subject query
    # 2
    # RESPONSE
    # case update schemas
    # parent

    # end point take from /sevices

    caseQuerySuccessResponse:
      description: When a list of Ids was NOT specified
      type: object
      properties:
        statusCode:
          type: string
        message:
          type: string
        ids:
          type: array
          items:
            type: string

    caseSubjectQuerySuccessResponse:
      description: When a list of Ids was specified
      type: object
      properties:
        statusCode:
          type: string
        message:
          type: string
        invalidIds:
          type: array
          items:
            type: string
        response:
          type: array
          items:
            $ref: "#/components/schemas/caseSubjectQuerySchema"

    # 1st child
    caseSubjectQuerySchema:
      type: object
      properties:
        CaseId:
          type: string
        ReporterType:
          type: string
        Type:
          type: string
        SFOriginalCaseId:
          type: string
        CSCaseId:
          type: string
        CSOriginalCaseId:
          type: string
        URLSalesforceCase:
          type: string
        ReporterName:
          type: string
        ReporterEmail:
          type: string
        ReportereBayMemberId:
          type: string
        PageURL:
          type: string
        CaseSubjectIds:
          type: array
          items:
            type: object
            properties:
              Id:
                type: string
        CaseSubjects:
          type: array
          items:
            type: object
            properties:
              CaseSubject:
                type: object
                properties:
                  Issue_URL__c:
                    type: string
                  TR_Portal__c:
                    type: string
                  Original_Case_Subject__c:
                    type: string
                  Id:
                    type: string
                  Case__c:
                    type: string
                  attributes:
                    type: object
                    properties:
                      url:
                        type: string
                      type:
                        type: string
    # end case subject query

    # case update
    # 3
    # REQUEST
    # case update request
    caseUpdateRequestBody:
      type: object
      properties:
        CaseSubjectIds:
          type: string
        CSCaseId:
          type: string
        Action Id:
          type: string
        Action Description:
          type: string
        Policy Id:
          type: string
        Policy Description:
          type: string
        Content ID:
          type: string
    caseUpdateSucessResponse:
      type: object
      properties:
        statusCode:
          type: string
          example: 200
        message:
          type: object
          properties:
            Success:
              type: object
              properties:
                CaseSubjectIds:
                  type: array
                  items:
                    type: string
                TR_Portal_Values:
                  type: object
                  example: { a0YD7000004ER3WMAW: Trusted Flagger }
            Failed:
              type: object

paths:
  /services/apexrest/port-services/casequery/tf:
    post:
      summary: get recent cases ID within 10mins
      security:
        - Bearer-Auth: []
      requestBody:
        description: Return a list of salesforce case record id
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  example: {}
                - $ref: "#/components/schemas/caseQuerySubjectRequestBody"
            examples:
              without subject: {}
              with subject:
                value: { ids: [500D700000MGsqqIAD, 500D800000MGsqqIAD] }

      responses:
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedResponse"
        "200":
          description: List of case id specifying in the request
          content:
            application/json:
              examples:
                without id response:
                  value: { statusCode: string, message: string, ids: [string] }
                with id response:
                  value:
                    {
                      statusCode: string,
                      message: string,
                      invalidIds: [string],
                      response:
                        [
                          {
                            CaseId: string,
                            ReporterType: string,
                            Type: string,
                            SFOriginalCaseId: string,
                            CSCaseId: string,
                            CSOriginalCaseId: string,
                            URLSalesforceCase: string,
                            ReporterName: string,
                            ReporterEmail: string,
                            ReportereBayMemberId: string,
                            PageURL: string,
                            CaseSubjectIds: [{ Id: string }],
                            CaseSubjects:
                              [
                                {
                                  CaseSubject:
                                    {
                                      Issue_URL__c: string,
                                      TR_Portal__c: string,
                                      Original_Case_Subject__c: string,
                                      Id: string,
                                      Case__c: string,
                                      attributes: { url: string, type: string },
                                    },
                                },
                              ],
                          },
                        ],
                    }
              schema:
                oneOf:
                  - $ref: "#/components/schemas/caseSubjectQuerySuccessResponse"
                  - $ref: "#/components/schemas/caseQuerySuccessResponse"

  /services/apexrest/port-services/caseupdate/tf:
    patch:
      summary: enpoint for case subject update
      security:
        - Bearer-Auth: []

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/caseUpdateRequestBody"

      responses:
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedResponse"

        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/caseUpdateSucessResponse"
