openapi: "3.0.2"
info:
  title: TF Inbound Salesforce API
  version: "1.0"
  description: Everythings about case query, case subject query, and case update of TF
servers:
  - url: https://ocioplatform--regulatory.sandbox.my.salesforce.com

tags:
  - name: TF PORT Inbound Subscriber

components:
  securitySchemes:
    Bearer-Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # global schema
    Unauthorized Response:
      type: object
      properties:
        message:
          type: string
          example: Session expired or invalid
        errorCode:
          type: string
          example: INVALID_SESSION_ID
    # case query
    # end case query

    # without Ids filter
    # with Ids filter
    With Ids Filter RequestBody:
      type: object
      description: List of salesforce case record id
      properties:
        ids:
          type: array
          items:
            type: string
      required:
        - "ids"

    # case subject query
    # 2
    # RESPONSE
    # case update schemas
    # parent

    # end point take from /sevices

    caseQuerySuccessResponse:
      description: When a list of Ids was NOT specified
      type: object
      properties:
        statusCode:
          type: string
        message:
          type: string
        ids:
          type: array
          items:
            type: string

    caseQueryIdsSuccessResponse:
      description: When a list of Ids was specified
      type: object
      properties:
        statusCode:
          type: string
        message:
          type: string
        invalidIds:
          type: array
          items:
            type: string
        response:
          type: array
          items:
            $ref: "#/components/schemas/caseQueryIdsSchema"

    # 1st child
    caseQueryIdsSchema:
      type: object
      properties:
        CaseId:
          type: string
        ReporterType:
          type: string
        Type:
          type: string
        SFOriginalCaseId:
          type: string
        CSCaseId:
          type: string
        CSOriginalCaseId:
          type: string
        URLSalesforceCase:
          type: string
        ReporterName:
          type: string
        ReporterEmail:
          type: string
        ReportereBayMemberId:
          type: string
        PageURL:
          type: string
        CaseSubjectIds:
          type: array
          items:
            type: object
            properties:
              Id:
                type: string
        CaseSubjects:
          type: array
          items:
            type: object
            properties:
              CaseSubject:
                type: object
                properties:
                  Issue_URL__c:
                    type: string
                  TR_Portal__c:
                    type: string
                  Original_Case_Subject__c:
                    type: string
                  Id:
                    type: string
                  Case__c:
                    type: string
                  attributes:
                    type: object
                    properties:
                      url:
                        type: string
                      type:
                        type: string
    # end case subject query

    # case update
    # 3
    # REQUEST
    # case update request
    caseUpdateRequestBody:
      type: object
      properties:
        CaseSubjectId:
          type: string
          description: This is salesforce case subject id.
        CSCaseId:
          type: string
        Action Id:
          type: string
        Action Description:
          type: string
        Policy Id:
          type: string
        Policy Description:
          type: string
        Content ID:
          type: string
    caseUpdateSucessResponse:
      type: object
      properties:
        statusCode:
          type: string
          example: 200
        message:
          type: object
          properties:
            Success:
              type: object
              properties:
                CaseSubjectIds:
                  type: array
                  items:
                    type: string
                TR_Portal_Values:
                  type: object
                  properties:
                    string:
                      type: string
                  example: { Case Subject Id: Trusted Flagger }
            Failed:
              type: object
              properties:
                CaseSubjectIds:
                  type: array
                  items:
                    type: string
                errors:
                  type: array
                  items:
                    type: string

    caseSubjectQuerySuccessResponse:
      type: object
      properties:
        statusCode:
          type: string
        message:
          type: string
        invalidIds:
          type: array
          items:
            type: string
        response:
          type: array
          items:
            $ref: "#/components/schemas/caseSubjectQueryItemResponse"

    caseSubjectQueryItemResponse:
      type: object
      properties:
        CaseSubjectId:
          type: string
        SFOriginalCaseId:
          type: string
        CSCaseId:
          type: string
        CSOrginalCaseId:
          type: string
        ReportType:
          type: string
        ContentId:
          type: string
        TRPortal:
          type: string
        PageURL:
          type: string
        ReasonCode:
          type: string
        URLSalesforceCase:
          type: string
        IssueSummary:
          type: string
        eBayItemNumber:
          type: string
        MessageToeBay:
          type: string
        MessageToSeller:
          type: string
        MessageToBuyer:
          type: string
        Name1:
          type: string
        Name2:
          type: string
        Documents:
          type: array
          items:
            type: string
            description: (List of document ids of case subject)
        OrginalDocuments:
          type: array
          items:
            type: string
            description: (List of orginal document ids of orginal case subject)
paths:
  /services/apexrest/port-services/casequery/tf:
    post:
      tags:
        - TF PORT Inbound Subscriber
      summary: Get recent cases ID within 10mins
      security:
        - Bearer-Auth: []
      requestBody:
        description: Return a list of salesforce case record ids
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  additionalProperties: false
                - $ref: "#/components/schemas/With Ids Filter RequestBody"
            examples:
              Witout Ids Filter: {}
              With Ids Filter:
                value: { ids: [string, string] }

      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ids
                  invalidIds:
                    type: array
                    items:
                      type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized Response"
        "200":
          description: Successfull Request
          content:
            application/json:
              examples:
                Without Ids filter in request:
                  value: { statusCode: string, message: string, ids: [string] }
                With Ids filter in request:
                  value:
                    {
                      statusCode: string,
                      message: string,
                      invalidIds: [string],
                      response:
                        [
                          {
                            CaseId: string,
                            ReporterType: string,
                            Type: string,
                            SFOriginalCaseId: string,
                            CSCaseId: string,
                            CSOriginalCaseId: string,
                            URLSalesforceCase: string,
                            ReporterName: string,
                            ReporterEmail: string,
                            ReportereBayMemberId: string,
                            PageURL: string,
                            CaseSubjectIds: [{ Id: string }],
                            CaseSubjects:
                              [
                                {
                                  CaseSubject:
                                    {
                                      Issue_URL__c: string,
                                      TR_Portal__c: string,
                                      Original_Case_Subject__c: string,
                                      Id: string,
                                      Case__c: string,
                                      attributes: { url: string, type: string },
                                    },
                                },
                              ],
                          },
                        ],
                    }
              schema:
                oneOf:
                  - $ref: "#/components/schemas/caseQueryIdsSuccessResponse"
                  - $ref: "#/components/schemas/caseQuerySuccessResponse"

  /services/apexrest/port-services/casesubjectquery/tf:
    post:
      tags:
        - TF PORT Inbound Subscriber
      summary: Get detail about each case including document
      security:
        - Bearer-Auth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/With Ids Filter RequestBody"

      responses:
        "200":
          description: Successfull Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/caseSubjectQuerySuccessResponse"

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Empty or invalid request body
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized Response"

  /services/apexrest/port-services/caseupdate/tf:
    patch:
      tags:
        - TF PORT Inbound Subscriber
      summary: Update report items in Trusted Flagger
      security:
        - Bearer-Auth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Case:
                  type: array
                  items:
                    $ref: "#/components/schemas/caseUpdateRequestBody"

      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The Case with Id 'a0YD7000004ER3WMA' is not a valid record type of 'Trusted Flagger Request'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized Response"

        "200":
          description: Successfull Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/caseUpdateSucessResponse"
